spring:
  datasource:
    url: jdbc:postgresql://localhost/dametran
    username: postgres
    password: postgres
    hikari:
      auto-commit: false
  h2:
    console:
      enabled: true
      path: /h2-console
  flyway:
    locations: classpath:db/migration/postgres

logging.file: dametran.log
logging:
  file:
    max-size: 50MB
    max-history: 10
  level:
    root: info
    org.springframework: info
    org.hibernate: info
    org.hibernate.SQL: debug
    org.thymeleaf: debug
    org.thymeleaf.TemplateEngine.CONFIG: trace
    org.thymeleaf.TemplateEngine.TIMER: trace
    org.thymeleaf.TemplateEngine.cache.TEMPLATE_CACHE: trace
    sample.java.damebatis: debug

management:
  endpoints:
    web:
      exposure:
        include: env,beans,loggers,info,health