spring:
  application:
    name: Demo project for Spring Boot with WebAuthn, MyBatis and Thymeleaf
  profiles:
    active: local
  output:
    ansi:
      enabled: detect
  datasource:
    url: jdbc:h2:mem:webauthn;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    username: sa
    password:
    hikari:
      auto-commit: false
  #  jpa:
  #    open-in-view: true
  #    generate-ddl: true
  #    hibernate:
  #      ddl-auto: create-drop
  jackson:
    serialization:
      indent-output: true
      write-dates-as-timestamps: false
      write-durations-as-timestamps: true
  thymeleaf:
    enabled: true
    encoding: UTF-8
    enable-spring-el-compiler: true
    mode: html
  devtools:
    restart:
      enabled: true
      log-condition-evaluation-delta: true
    livereload:
      enabled: false
  h2:
    console:
      enabled: true
      path: /h2-console
  messages:
    basename: i18n/application-messages
    encoding: UTF-8

server:
  port: 55501

logging.file: dametran.log
logging:
  file:
    max-size: 50MB
    max-history: 10
  level:
    root: info
    org.springframework: info
    org.hibernate: info
    org.hibernate.SQL: info
    org.thymeleaf: info
    org.thymeleaf.TemplateEngine.CONFIG: info
    org.thymeleaf.TemplateEngine.TIMER: info
    org.thymeleaf.TemplateEngine.cache.TEMPLATE_CACHE: info
    sample.java.damebatis: info
